apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: conversationstore
  namespace: agents
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-dev-redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    value: "6s5jPTxZhN"
