apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: conversationstore
  namespace: agents
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-dev-redis-master.default.svc.cluster.local:6379
  # https://docs.dapr.io/operations/components/component-secrets/
  - name: redisPassword
    #value: "***" # put your redis password here
    secretKeyRef:
      name: dapr-dev-redis
      key: redis-password
auth:
  secretStore: kubernetes # SECRET_STORE_NAME is the name of the configured secret store component. When running in Kubernetes and using a Kubernetes secret store, the field auth.SecretStore defaults to kubernetes and can be left empty.