apiVersion: v1
kind: Service
metadata:
  name: mcp-svc
  namespace: agents
spec:
  type: ClusterIP
  selector:
    app: mcp-agent-pg-openai-server-mcp
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
