apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-llm
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: ollama-llm
  template:
    metadata:
      labels:
        name: ollama-llm
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ollama-llm-dapr"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "11434"
        dapr.io/sidecar-inject: "true"
        dapr.io/sidecar-inject-annotation: "true"
        dapr.io/sidecar-liveness-probe-delay-second: "180" # it takes some time to create ollama container
        dapr.io/sidecar-liveness-probe-timeout-seconds: "300"
        dapr.io/config: "tracing" # zipkin tracing configuration
    spec:
      containers:
      - name: ollama-llm
        image: ollama/ollama:latest
        env:
        - name: OLLAMA_NUM_THREADS
          value: "4"
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", " ollama pull all-minilm ; sleep 5 ; ollama run llama3.2:1b ; sleep 5"]