apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-pvc
  namespace: pgvector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: manual
