apiVersion: batch/v1
kind: CronJob
metadata:
  name: dapr-sdk-docs-scraper
  namespace: agents
spec:
  schedule: "* 9 * * *" # Every day at 9 AM
  # schedule: "*/10 * * * *" # Every 10 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dapr-sdk-docs-scraper
          annotations:
            dapr.io/enabled: "true"
            dapr.io/app-id: "dapr-sdk-docs-scraper"
            dapr.io/enable-api-logging: "true"
            dapr.io/sidecar-inject: "true"
            dapr.io/sidecar-inject-annotation: "true"
            dapr.io/config: "tracing" # zipkin tracing configuration
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scraper
            image: localhost:32000/injection-agent-web-dapr:latest  # Replace with your image
            imagePullPolicy: IfNotPresent
            env:
            - name: LOG_LEVEL
              value: "INFO"
            envFrom:
            - configMapRef:
                name: dapr-scraper-config-dapr
            - secretRef:
                name: pg-secret-dapr