apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb-agents-connection
  namespace: agents
spec:
  type: bindings.postgres
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: pg-secret-dapr
        key: connectionString
    - name: direction
      value: "input, output"
scopes:
  - dapr-sdk-docs-scraper # This is the name of the Dapr application that will use this binding
  - docs-sync # This is the name of the Dapr application that will use this binding