apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dapr-secret-reader
  namespace: pgvector # This role applies only to the 'agents' namespace
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "list", "watch"] # "get" is needed to read a specific secret, "list" and "watch" are often useful tooapiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dapr-secret-reader
  namespace: pgvector # This role applies only to the 'agents' namespace
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "list", "watch"] # "get" is needed to read a specific secret, "list" and "watch" are often useful too..
