apiVersion: v1
kind: Namespace
metadata:
  name: agents
---
apiVersion: v1
data:
  DAPR_BINDING_NAME: pgdb-agents-connection
  DB_HOST: pgvector.pgvector.svc.cluster.local
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_TABLE: dapr_web
  JSON_FILE: dapr_docs_dev.json
  SCRAPY_TARGET_PATH: dapr_docs_web
  SITEMAP_URL: https://docs.dapr.io/en/sitemap.xml
kind: ConfigMap
metadata:
  name: dapr-scraper-config-dapr
  namespace: agents
---
apiVersion: v1
data:
  connectionString: |
    dXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wZ3ZlY3RvciBob3N0PXBndmVjdG9yLnBndmVjdG
    9yLnN2Yy5jbHVzdGVyLmxvY2FsIHBvcnQ9NTQzMiBkYm5hbWU9cG9zdGdyZXMgcG9vbF9t
    aW5fY29ubnM9MSBwb29sX21heF9jb25ucz0xMA==
kind: Secret
metadata:
  name: pg-secret-dapr
  namespace: agents
type: Opaque
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dapr-sdk-docs-scraper
  namespace: agents
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            dapr.io/app-id: dapr-sdk-docs-scraper
            dapr.io/enable-api-logging: "true"
            dapr.io/enabled: "true"
            dapr.io/sidecar-inject: "true"
            dapr.io/sidecar-inject-annotation: "true"
          labels:
            app: dapr-sdk-docs-scraper
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: dapr-scraper-config-dapr
            - secretRef:
                name: pg-secret-dapr
            image: localhost:32000/my-scraper-image-dapr:latest  # Replace with your image
            imagePullPolicy: IfNotPresent
            name: scraper
          restartPolicy: OnFailure
  schedule: "* 9 * * *" # Every day at 9 AM
  # schedule: "*/10 * * * *" # Every 10 minutes
  successfulJobsHistoryLimit: 2
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb-agents-connection
  namespace: agents
scopes:
- dapr-sdk-docs-scraper
spec:
  metadata:
  - name: connectionString
    secretKeyRef:
      key: connectionString
      name: pg-secret-dapr
  - name: direction
    value: input, output
  type: bindings.postgres
  version: v1
