apiVersion: apps/v1
kind: CronJob
metadata:
  name: dapr-docs-scraper
  namespace: agents
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: 2-injection-agent-web
          image: localhost:32000//injection-agent-web-dapr:latest # Replace with your image