apiVersion: v1
data:
  DB_HOST: pgvector.pgvector.svc.cluster.local
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_TABLE: dapr_web
  JSON_FILE: dapr_docs_dev.json
  SCRAPY_TARGET_PATH: dapr_docs_web
  SITEMAP_URL: https://docs.dapr.io/en/sitemap.xml
kind: ConfigMap
metadata:
  name: dapr-scraper-config
  namespace: agents
---
apiVersion: v1
data:
  DB_PASSWORD: cGd2ZWN0b3I=
  DB_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: dapr-scraper-secret
  namespace: agents
type: Opaque
---
apiVersion: v1
data:
  connectionString: |
    dXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wZ3ZlY3RvciBob3N0PXBndmVjdG9yLnBndmVjdG
    9yLnN2Yy5jbHVzdGVyLmxvY2FsIHBvcnQ9NTQzMiBkYm5hbWU9cG9zdGdyZXMgcG9vbF9t
    aW5fY29ubnM9MSBwb29sX21heF9jb25ucz0xMA==
kind: Secret
metadata:
  name: pg-secret
  namespace: agents
type: Opaque
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dapr-docs-scraper
  namespace: agents
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dapr-docs-scraper
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: dapr-scraper-config
            - secretRef:
                name: dapr-scraper-secret
            image: localhost:32000/my-scraper-image
            imagePullPolicy: IfNotPresent
            name: scraper
          restartPolicy: OnFailure
  schedule: 5 * * * *
  successfulJobsHistoryLimit: 2
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb-agents-connection
  namespace: agents
scopes:
- guess-film-noagent
- my-dapr-web-scraper
spec:
  metadata:
  - name: connectionString
    secretKeyRef:
      key: connectionString
      name: pg-secret
  - name: direction
    value: input, output
  type: bindings.postgres
  version: v1
