apiVersion: v1
kind: Namespace
metadata:
  name: agents
---
apiVersion: v1
data:
  DAPR_BINDING_NAME: pgdb-agents-connection
  DB_HOST: pgvector.pgvector.svc.cluster.local
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_TABLE: dapr_web
  OLLAMA_DAPR_SERVICE_NAME: ollama-llm-dapr.ollama
  OLLAMA_EMBEDDING_MODEL: all-minilm
  OLLAMA_HOST: http://ollama.ollama.svc.cluster.local
  OLLAMA_MODEL: llama3.2:1b
  OLLAMA_PORT: "11434"
kind: ConfigMap
metadata:
  name: user-web-config
  namespace: agents
---
apiVersion: v1
data:
  connectionString: |
    dXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wZ3ZlY3RvciBob3N0PXBndmVjdG9yLnBndmVjdG
    9yLnN2Yy5jbHVzdGVyLmxvY2FsIHBvcnQ9NTQzMiBkYm5hbWU9cG9zdGdyZXMgcG9vbF9t
    aW5fY29ubnM9MSBwb29sX21heF9jb25ucz0xMA==
kind: Secret
metadata:
  name: pg-secret-dapr
  namespace: agents
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: user-web-dapr
  namespace: agents
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: user-web-dapr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-web-dapr
  name: user-web-dapr
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-web-dapr
  template:
    metadata:
      annotations:
        dapr.io/app-id: user-web-dapr
        dapr.io/enable-api-logging: "true"
        dapr.io/enabled: "true"
        dapr.io/sidecar-inject: "true"
        dapr.io/sidecar-inject-annotation: "true"
        dapr.io/sidecar-liveness-probe-delay-second: "10"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "70"
        dapr.io/config: "tracing" # zipkin tracing configuration
      labels:
        app: user-web-dapr
    spec:
      containers:
      - name: user-web-dapr
        image: localhost:32000/user-web-dapr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: LOG_LEVEL
          value: "INFO"
        envFrom:
        - configMapRef:
            name: user-web-config
        - secretRef:
            name: pg-secret-dapr
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai-llm-model
  namespace: agents
spec:
  type: conversation.openai
  version: v1
  metadata:
  - name: key
    secretKeyRef:
      name: openai-api-key # The name of your K8s secret (e.g., 'my-openai-key')
      key: dapr         # The key *within* that K8s secret (e.g., 'api-key') Created in https://platform.openai.com/api-keys
  - name: model
    value: gpt-4.1-nano
    #value: gpt-4.1-nano-2025-04-14 # GPT-4.1 nano is the fastest, most cost-effective GPT-4.1 model.
  - name: cacheTTL
    value: 10m
  # - name: scrubPII
  #   value: "true" #Optional. Will obfuscate any sensitive information returning from the LLM
  # - name: temperature
  #   value: 0 # 0.5 // Optional. Optimizes for consistency (0) or creativity (1)
scopes:
  - user-web-dapr # This is the name of the Dapr application that will use
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb-agents-connection
  namespace: agents
scopes:
- user-web-dapr
- dapr-sdk-docs-scraper
spec:
  metadata:
  - name: connectionString
    secretKeyRef:
      key: connectionString
      name: pg-secret-dapr
  - name: direction
    value: input, output
  type: bindings.postgres
  version: v1
