apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-docs-scraper
  namespace: agents
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: user-web-dapr
          image: localhost:32000/user-web-dapr:latest