apiVersion: apps/v1
kind: CronJob
metadata:
  name: dapr-docs-scraper
  namespace: agents
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: user-web
          image: localhost:32000/user-web:latest