apiVersion: v1
data:
  DB_HOST: pgvector.pgvector.svc.cluster.local
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_TABLE: dapr_web
  JSON_FILE: dapr_docs.json
  SCRAPY_TARGET_PATH: dapr_docs_web
  SITEMAP_URL: https://docs.dapr.io/en/sitemap.xml
kind: ConfigMap
metadata:
  name: dapr-scraper-config
  namespace: agents
---
apiVersion: v1
data:
  DB_PASSWORD: cGd2ZWN0b3I=
  DB_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: dapr-scraper-secret
  namespace: agents
type: Opaque
---
apiVersion: v1
data:
  connectionString: |
    ICJ1c2VyPXBvc3RncmVzIHBhc3N3b3JkPXBndmVjdG9yIGhvc3Q9cGd2ZWN0b3IucGd2ZW
    N0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwgcG9ydD01NDMyIGRibmFtZT1kdmRyZW50YWwgcG9v
    bF9taW5fY29ubnM9MSBwb29sX21heF9jb25ucz0xMCI=
kind: Secret
metadata:
  name: pg-secret
  namespace: agents
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-docs-scraper
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-docs-scraper
  template:
    metadata:
      labels:
        app: dapr-docs-scraper
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: dapr-scraper-config
        - secretRef:
            name: dapr-scraper-secret
        image: localhost:32000/my-scraper-image:latest
        imagePullPolicy: IfNotPresent
        name: scraper
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb-dvdrental
  namespace: agents
scopes:
- guess-film-noagent
spec:
  metadata:
  - name: connectionString
    secretKeyRef:
      key: connectionString
      name: pg-secret
  - name: direction
    value: input, output
  type: bindings.postgres
  version: v1
