apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: agents
type: Opaque
stringData:
  connectionString: "user=postgres password=pgvector host=pgvector.pgvector.svc.cluster.local port=5432 dbname=dvdrental pool_min_conns=1 pool_max_conns=10"
