namePrefix: prod-

resources:
  - ../../base

configMapGenerator:
  - name: dapr-scraper-config
    behavior: merge
    literals:
      - DB_NAME=prod_db
      - DB_HOST=postgres-prod
      - DB_PORT=5432
      - DB_TABLE=dapr_web_prod
      - SITEMAP_URL=https://docs.dapr.io/en/sitemap.xml
      - JSON_FILE=dapr_docs_prod.json
      - SCRAPY_TARGET_PATH=dapr_docs_web

secretGenerator:
  - name: dapr-scraper-secret
    behavior: merge
    literals:
      - DB_USER=prod_user
      - DB_PASSWORD=secureProdPassword
