apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb-agents-connection
  namespace: agents
spec:
  type: bindings.postgres
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: pg-secret
        key: connectionString
    - name: direction
      value: "input, output"
scopes:
  - guess-film-noagent
  - my-dapr-web-scraper
