# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dapr-docs-scraper
#   namespace: agents
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: dapr-docs-scraper
#   template:
#     metadata:
#       labels:
#         app: dapr-docs-scraper
#     spec:
#       containers:
#       - name: scraper
#         image: my-scraper-image:latest  # Replace with your image
#         imagePullPolicy: IfNotPresent
#         envFrom:
#         - configMapRef:
#             name: dapr-scraper-config
#         - secretRef:
#             name: dapr-scraper-secret
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dapr-docs-scraper
  namespace: agents
spec:
  schedule: "5 * * * *"  # Every hour at minute 5
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dapr-docs-scraper
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scraper
            image: injection-agent-web-dapr:latest  # Replace with your image
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: dapr-scraper-config
            - secretRef:
                name: dapr-scraper-secret