# https://docs.dapr.io/operations/observability/tracing/tracing-overview/
# see https://docs.dapr.io/operations/observability/tracing/zipkin/
# https://zipkin.io/
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"