apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-web-dapr
  labels:
    app: user-web-dapr
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-web-dapr
  template:
    metadata:
      labels:
        app: user-web-dapr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "user-web-dapr"
        dapr.io/enable-api-logging: "true"
        #dapr.io/config: "user-web-dapr" # Tells Dapr which Configuration resource to use
        dapr.io/sidecar-inject: "true"
        dapr.io/sidecar-inject-annotation: "true"
        dapr.io/sidecar-liveness-probe-delay-second: "10"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "70"
    spec:
      containers:
      - name: user-web-dapr
        image: localhost:32000/user-web-dapr:latest  # Replace with your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: user-web-config
        - secretRef:
            name: pg-secret-dapr
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"